- name: Disable swap
  command: swapoff -a

- name: Comment out swap line in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*swap.*)$'
    replace: '# \1'

- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Ensure kernel modules are loaded
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Set sysctl params for Kubernetes networking
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply sysctl parameters
  command: sysctl --system

- name: Install containerd dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes
    state: present

- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Generate default containerd config
  command: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Set SystemdCgroup = true in containerd config
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart and enable containerd
  systemd:
    name: containerd
    state: restarted
    enabled: true

- name: Ensure required directories exist
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download and install Kubernetes APT GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
  register: kubernetes_key

- name: Add Kubernetes APT repository (New repo for v1.32+)
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [trusted=yes] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
    mode: '0644'

- name: Install kubeadm, kubelet, and kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes
    state: present
