---
# k8s require to use systemd cgroup, might conflict with cgroupfs
# sudo containerd config default | sudo tee /etc/containerd/config.toml
#[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  #SystemdCgroup = true
#sudo systemctl restart containerd

- name: Install container runtime and kube
  import_tasks: install-aws-ec2.yaml

- name: Configure Kubernetes master
  import_tasks: init-master.yaml
  when: "'masters' in group_names"

- name: Configure Kubernetes workers
  import_tasks: add-workers.yaml
  when: "'workers' in group_names"
